### ISSUE TITLE
Bandwidth Limiting

### ISSUE THREAD

**Issue by Eric-Marchetti** [Team1559/2020-InfiniteRecharge#17]
Adjust camera settings so we meet the 4Mb/sec bandwidth limit with some headroom. Suggest we aim for 3 Mb/sec while the camera is moving. Figure out how to make those settings persistent so the robot uses the correct settings by default.

**Comment by mmarchetti** [comment]
Take a look at the docs here: https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/cscore/VideoSource.html.

You can call `camera.setResolution` and `camera.setFPS` to set the resolution of each camera stream. You might also need to set the dashboard camera display to the same resolution.

**Comment by mmarchetti** [comment]
Have we verified that we're under the bandwidth limit?
