### ISSUE TITLE
Set Chassis Motors to Velocity Mode

### ISSUE THREAD

**Issue by SonicDRJ** [Team1559/2020-InfiniteRecharge#38]
Currently, the motors for the chassis run in percent output mode... this is unacceptable... we need to convert it to velocity mode at some point!!!!

**Comment by mmarchetti** [comment]
Chassis initial testing tonight shows the importance of this. When you let go of the sticks, the robot does not stop. Using brake mode would help a little, but with the full robot mass it won't be enough. Velocity mode will apply reverse power to stop the robot quickly (once we get the PID controller tuned).

**Comment by mmarchetti** [comment]
The strategy we used last year was to copy the base drive chassis code from WPILib into a new file / new class in our robot, and within there, change the `set` call from percent output to velocity mode. The WPILib code we are using is here: https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
