### ISSUE TITLE
PowerCell should not import Robot

### ISSUE THREAD

**Issue by mmarchetti** [Team1559/2020-InfiniteRecharge#48]
The Robot depends on the subsystems. The subsystems should not depend on/import the Robot. PowerCell currently does this in order to access the operator interface. A better method would be for the Robot to pass its operator interface to the PowerCell constructor. The PowerCell can keep a reference to the OI around and access it as needed.

**Comment by thadwojcik** [comment]
Agree with @mmarchetti - @Rylan-Meilutis made the OI static reference you can simply refer to it globally by doing Robot.oi.whatever in your class. @JordanCieslinski has an example in his soon to be committed Spinner class

**Comment by Rylan-Meilutis** [comment]
I have made that change in the climber branch and when that branch makes a PR it should be fixed.

**Comment by mmarchetti** [comment]
Let's discuss tomorrow - I think we meant something a little different. 

In robot.java, pass the operator interface into the subsystem constructor:
```
    oi = new OperatorInterface();
    powerCell = new PowerCell(oi);
```

In the subsystem, keep a reference to the operator interface:
```
    OperatorInterface oi;
    ...
    PowerCell(OperatorInterface _oi) {
        oi = _oi;
    }
    public void drive() {
        if oi.getRawButton(...)...
    }
```

**Comment by mmarchetti** [comment]
Help avoid circular dependencies/imports (Robot depends on PowerCell which depends on Robot). The subsystems should not need to `import frc.robot.Robot`.
