### ISSUE TITLE
Change climber from velocity to percent output

### ISSUE THREAD

**Issue by Rylan-Meilutis** [Team1559/2020-InfiniteRecharge#54]

**Comment by mmarchetti** [comment]
I like that you created an issue to track this work. We should also discuss what control mode we want for the winch motor - it's not clear that it should be in velocity mode. We might be able to simply run in percent output with a current limit, and a limit switch. Let's talk with Chris tomorrow.

**Comment by Rylan-Meilutis** [comment]
Sounds good

**Comment by mmarchetti** [comment]
It looks like the winch is still set to velocity mode in several places in Climber.java - can you check and re-open the issue if needed?
